name: Auto merge

on:
  schedule:
    # Run at 00:16 every day
    - cron:  '00 19 * * *'


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge dev -> main
        uses: devmasx/merge-branch@master
        with:
          from_branch: 'dev'
          target_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main -> dev
        uses: devmasx/merge-branch@master
        with:
          from_branch: 'main'
          target_branch: 'dev'
          github_token: ${{ secrets.GITHUB_TOKEN }}